#pragma once
#include <vulkan/vulkan_core.h>

extern PFN_vkGetPhysicalDeviceProperties originalVkGetPhysicalDeviceProperties;
extern PFN_vkGetPhysicalDeviceProperties2 originalVkGetPhysicalDeviceProperties2;
extern PFN_vkGetPhysicalDeviceProperties2KHR originalVkGetPhysicalDeviceProperties2KHR;
extern PFN_vkGetPhysicalDeviceFeatures2 originalVkGetPhysicalDeviceFeatures2;
extern PFN_vkGetPhysicalDeviceQueueFamilyProperties originalVkGetPhysicalDeviceQueueFamilyProperties;
extern PFN_vkEnumerateInstanceExtensionProperties originalVkEnumerateInstanceExtensionProperties;
extern PFN_vkEnumerateDeviceExtensionProperties originalVkEnumerateDeviceExtensionProperties;
extern PFN_vkCreateDevice originalVkCreateDevice;
extern PFN_vkQueuePresentKHR originalVkQueuePresentKHR ;
extern PFN_vkWaitSemaphores originalVkWaitSemaphores;
extern PFN_vkWaitSemaphoresKHR originalVkWaitSemaphoresKHR;
void proxy_VkGetPhysicalDeviceProperties(VkPhysicalDevice physical_device, VkPhysicalDeviceProperties* properties);
void proxy_VkGetPhysicalDeviceProperties2(VkPhysicalDevice phys_dev, VkPhysicalDeviceProperties2* properties2);
void proxy_VkGetPhysicalDeviceProperties2KHR(VkPhysicalDevice phys_dev, VkPhysicalDeviceProperties2* properties2);
void VKAPI_PTR proxy_VkGetPhysicalDeviceFeatures2(VkPhysicalDevice physicalDevice, VkPhysicalDeviceFeatures2* pFeatures);
void VKAPI_PTR proxy_VkGetPhysicalDeviceQueueFamilyProperties(VkPhysicalDevice physicalDevice, uint32_t* pQueueFamilyPropertyCount, VkQueueFamilyProperties* pQueueFamilyProperties);
VkResult VKAPI_PTR proxy_VkCreateDevice(VkPhysicalDevice physicalDevice, VkDeviceCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkDevice* pDevice);
VkResult proxy_VkEnumerateInstanceExtensionProperties(const char* pLayerName, uint32_t* pPropertyCount, VkExtensionProperties* pProperties);
VkResult proxy_VkEnumerateDeviceExtensionProperties(VkPhysicalDevice physicalDevice, const char* pLayerName, uint32_t* pPropertyCount, VkExtensionProperties* pProperties);

void Vulkan_HookDeviceFunctions();
